# Copyright (c) 2024, Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

name: Documentation

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        doxygen-version: [1.9.6, 1.14.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          DOXYGEN_VERSION="${{ matrix.doxygen-version }}"
          wget --no-verbose "https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VERSION//./_}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz"
          tar xf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
          echo "${PWD}/doxygen-${DOXYGEN_VERSION}/bin" >> $GITHUB_PATH
          pip install -r doc/requirements.txt

      - name: Build
        run: |
          cd doc
          doxygen

          SPHINXOPTS="-W" make html

          mkdir deploy
          mv _build_doxygen/html deploy/doxygen
          mv _build_sphinx/html/* deploy

      - name: Setup pages
        if: github.event_name != 'pull_request' && matrix.doxygen-version == '1.14.0'
        uses: actions/configure-pages@v4

      - name: Upload pages artifact
        if: github.event_name != 'pull_request' && matrix.doxygen-version == '1.14.0'
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/deploy

      - name: Upload artifacts
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: docs-doxygen-${{ matrix.doxygen-version }}
          path: doc/deploy

  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    needs: build
    if: github.event_name != 'pull_request'
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
